#!/usr/bin/env bash
set -Eeuo pipefail
luser="allgreed"

if [ ! -d /home/$luser/Dotfiles ]; then
    git clone https://github.com/allgreed/dotfiles.git /home/$luser/Dotfiles 
fi

git --git-dir=/etc/nixos/.git remote set-url --push origin git@github.com:allgreed/nixos-config.git
git --git-dir=/home/$luser/Dotfiles/.git remote set-url --push origin git@github.com:allgreed/dotfiles.git

# I kindof like having it
mkdir -p /mnt

read -ep 'Hostname: ' hostname
hashed_password=$(mkpasswd -m sha512crypt)
read -ep 'Spotify username: ' spotify_username
read -ep 'Spotify password: ' spotify_password

# might not be necessary and should be fixed at some point
# https://github.com/NixOS/nix/issues/3356#issuecomment-1642611739
mkdir -p /nix/var/nix/profiles/per-user/$luser
chown $luser /nix/var/nix/profiles/per-user/$luser

tmp=$(mktemp)
cat <<EOF > $tmp
{ config, pkgs, ... }:

{
  # machine identification
  networking.hostName = "$hostname";
  networking.hostId = "$(head -c 8 /etc/machine-id)";

  # secrets
  users.users."$luser".hashedPassword = "$hashed_password";
  services.spotifyd.config = ''
    [global]
    username = "$spotify_username"
    password = "$spotify_password"
  '';
}
EOF

echo '=================================================='
echo 'Following contents will be written to ./local.nix:'
echo '=================================================='
cat $tmp


echo '===================='
echo 'The differences are:'
echo '===================='
diff '/etc/nixos/local.nix' $tmp || true

echo
read -p "Do you approve of this plan? (Y/nN) " -n 1 -r
echo

if [[ $REPLY =~ ^[Y]$ ]]
then
    if [ -f ./local.nix ]; then
        read -p "local.nix already exists, do you want to overwrite? (Y/nN) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Y]$ ]]
        then
            echo 'writing backup to ./local.nix.bak'
            mv -f '/etc/nixos/local.nix' '/etc/nixos/local.nix.bak'
        else
            exit
        fi
    fi

    mv --no-clobber $tmp '/etc/nixos/local.nix'
fi

chmod 600 '/etc/nixos/local.nix'

chmod --recursive 600 '/etc/nixos/setup'
chmod +xr '/etc/nixos/setup'
chmod 744 '/etc/nixos/setup/init'
